Handling Keyboard Interruption - Обработка прерываний клавиатуры

Новое в версии 3.11.

Когда signal.SIGINT вызывается нажатием Ctrl-C, в основном потоке по умолчанию возникает
исключение KeyboardInterrupt. Однако это не работает с asyncio, поскольку может прервать
внутреннюю работу asyncio и помешать выходу программы.

Чтобы решить эту проблему, asyncio обрабатывает signal.SIGINT следующим образом:

     1. asyncio.Runner.run() устанавливает собственный обработчик signal.SIGINT перед
    выполнением любого пользовательского кода и удаляет его при выходе из функции.

     2. Runner создает основную задачу для переданной сопрограммы для ее выполнения.

     3. Когда signal.SIGINT вызывается нажатием Ctrl-C, пользовательский обработчик
    сигнала отменяет основную задачу, вызывая asyncio.Task.cancel(), который вызывает 
    asyncio.CancelledError внутри основной задачи. Это приводит к тому, что стек Python
    разворачивается, и блоки try/Exception и try/finally можно использовать для очистки
    ресурсов. После отмены основной задачи asyncio.Runner.run() вызывает KeyboardInterrupt.

     4. Пользователь может написать плотный цикл, который не может быть прерван с помощью
    asyncio.Task.cancel(), и в этом случае второе следующее сочетание клавиш Ctrl-C 
    немедленно вызывает KeyboardInterrupt (Прерывание клавиатуры) без отмены основной задачи.